name: Python CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test-lint:
    runs-on: ubuntu-latest

    steps:
    - name: Kodları repodan çek
      uses: actions/checkout@v3

    - name: Python ortamını ayarla
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Bağımlılıkları yükle
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Kod kalitesini kontrol et PEP8 (flake8)
      run: |
        flake8 .

    - name: Unit testleri çalıştır (pytest)
      run: |
        pytest